apiVersion: v1
kind: Service
metadata:
  name: profiles-service
  namespace: fund-foresight
spec:
  selector:
    app: profiles-service
  ports:
    - protocol: TCP
      port: 7500
      targetPort: 7500
  type: ClusterIP