apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: navleensandhu/gateway
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: gateway-config
