apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: fund-foresight
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
