apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: fund-foresight
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
  selector:
    app: zookeeper
  type: ClusterIP
