apiVersion: v1
kind: Service
metadata:
  name: savings-service
  labels:
    app: savings-service
  namespace: fund-foresight
spec:
  selector:
    app: savings-service
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: ClusterIP