apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
  namespace: fund-foresight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: navleensandhu/auth-service
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-service-config
