server:
    port: ${PORT}
spring:
    application:
        name: notifications
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
transactions:
    api:
        url: ${TRANSACTIONS_URL}
budgets:
    api:
        url: ${BUDGETS_URL}
kafka:
    url: ${KAFKA_URL}