apiVersion: v1
kind: Service
metadata:
  name: budget-service
  namespace: fund-foresight
spec:
  selector:
    app: budget-service
  ports:
    - protocol: TCP
      port: 6500
      targetPort: 6500
  type: ClusterIP