export const countryCodes = [
    { name: "United States", code: "US" },
    { name: "United Kingdom", code: "GB" },
    { name: "Spain", code: "ES" },
    { name: "Netherlands", code: "NL" },
    { name: "France", code: "FR" },
    { name: "Ireland", code: "IE" },
    { name: "Canada", code: "CA" },
    { name: "Germany", code: "DE" },
    { name: "Italy", code: "IT" },
    { name: "Poland", code: "PL" },
    { name: "Denmark", code: "DK" },
    { name: "Norway", code: "NO" },
    { name: "Sweden", code: "SE" },
    { name: "Estonia", code: "EE" },
    { name: "Lithuania", code: "LT" },
    { name: "Latvia", code: "LV" },
    { name: "Portugal", code: "PT" },
    { name: "Belgium", code: "BE" },
];
