spring:
    application:
        name: transactions-service
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
notifications:
    url: ${NOTIFICATIONS_URL}
kafka:
    url: ${KAFKA_URL}