apiVersion: v1
kind: Service
metadata:
  name: transactions-service
  namespace: fund-foresight
spec:
  selector:
    app: transactions-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP