apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service
  labels:
    app: transactions-service
  namespace: fund-foresight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions-service
  template:
    metadata:
      labels:
        app: transactions-service
    spec:
      containers:
        - name: transactions-service
          image: navleensandhu/transactions-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: transactions-service-config
